import "./globals.css";
import { Appwrapper } from "./context/index";
import Navbar from "./Navbar/page";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Appwrapper>
          <Navbar />
          {children}
        </Appwrapper>
      </body>
    </html>
  );
}
